import type { Metadata } from "next";
// Correctly import Geist fonts from the 'geist' package
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
// Import Knewave from Google Fonts
import { Knewave } from "next/font/google";
import { Chicle } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";

// Knewave is now configured for headings
const knewave = Knewave({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-knewave",
});
const chicle = Chicle({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-chicle",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // All three font variables are now available to your CSS
        className={`${GeistSans.variable} ${GeistMono.variable} ${knewave.variable} ${chicle.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}